name: baddie
favicon: null
layout_spectrum: 0.9851352479308844
typography_spectrum: 0.22912609693594277
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.0936447971034795
  lightness: 0.20587747753597796
  saturation: 0.917536782566458
  rhythmicContrast: 0.014470734866335988
purpose: []
